apiVersion: gateway.networking.k8s.io/v1
kind: Gateway

metadata:
  name: app-service-mesh-gateway

spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
    allowedRoutes:
      namespaces:
        from: Same

