apiVersion: networking.istio.io/v1
kind: VirtualService

metadata:
  name: app-service-mesh-routes

spec:
  hosts:
  - app-service-mesh-svc.app.svc.cluster.local
  http:
  - name: "app-service-mesh-v2"
    match:
    - uri:
        prefix: "/teste"
    - uri:
        prefix: "/teste-2"
    rewrite:
      uri: "/healthz"
    route:
      - destination:
        host: pp-service-mesh-svc.app.svc.cluster.local
        subset: V2
  - name: "app-service-mesh-v1"
    route:
    - destination:
        host: pp-service-mesh-svc.app.svc.cluster.local
        subset: V1
    # - routes:
    #   - destination:
    #       host: app-service-mesh-svc.app.svc.cluster.local
    #       subset: V1
    #     weight: 50
    #   - destination:
    #       host: app-service-mesh-svc.app.svc.cluster.local
    #       subset: V2
    #     weight: 50